### ISSUE TITLE
Uncaught exception Unsupported swizzle read ".a"

### ISSUE THREAD

**Issue by rainyt** [haxiomic/vector-math#13]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/9693090/118386394-c0e47e80-b649-11eb-9e08-e8d6c6a87e7e.png">
Hi, This access is allowed in GLSL, but it is not.

**Comment by rainyt** [comment]
```haxe
color.r += 0.3;
color.b += sin(time / 60);        
```
There is also a problem with this.

**Comment by haxiomic** [comment]
Merged your PR, thank you :)
