### ISSUE TITLE
single precision types

### ISSUE THREAD

**Issue by shakesoda** [haxiomic/vector-math#2]
I can imagine this being out of scope since it's not available on all/generic targets, but it'd be useful to support `Single` (i.e. f32) type for perf/memory reasons on cs/cpp/java/hl when full f64 precision isn't required/desired.

**Comment by haxiomic** [comment]
This is a great idea, maybe behind a parameter `-D vector-math-single`? Although it might make sense for Single to be default, especially if these outputs are most likely used to set f32's in graphics APIs

**Comment by shakesoda** [comment]
a build flag would work great for me. it's a reasonable default for my usage but it might be better to leave it as f64 for consistency across targets, and maybe spare some people from running into unexpected precision (or runtime - hashlink jit has some rough edges here) bugs.

**Comment by haxiomic** [comment]
Added `-D vector_math_f32` in https://github.com/haxiomic/vector-math/commit/ed5aee7d19e466f54bde85f0a66c30506513c752

When used generated C++ code simply has `float` for vector vars
